### ISSUE TITLE
Search on multiple columnnames

### ISSUE THREAD

**Issue by WouterVdS** [thorbenprimke/realm-searchview#10]
First of all, great work! It's a pleasure to work with!
Maybe in a next update you can add an option so users are able to search in multiple columns at the same time? Looked into your source code and saw it doesn't work, but it can come in very handy I think. 

For example, I have a realm database with stores (store names, addresses,...) and I want one search field where users can simultaneously search for names and cities for example.

**Comment by A86S** [comment]
i am stuck with the same issue with realm and i did not find any answer , finally i managed it with ArrayList.

**Comment by WouterVdS** [comment]
I fixed it by adding a new field containing a concatenation of all the data in the object. A bit of a workaround, but it works!
