### ISSUE TITLE
How to use it without a filter key

### ISSUE THREAD

**Issue by paragones** [thorbenprimke/realm-searchview#13]
HI Thorben, 

You mentioned in your readme that realmsearchadapter can accept without any filter key. I've tried checking around and even asked SO but I didn't see how I can instantiate that adapter without the filter key. Is it possible to do it without filter key?

**Comment by reline** [comment]
@paragones You should be able to choose any field in your RealmObject to pass as the filter key, then just call `RealmSearchAdapter.filter("");` after you initialize your adapter to view all of the items in Realm.
