### ISSUE TITLE
Dublicate file exeption

### ISSUE THREAD

**Issue by mhgk** [thorbenprimke/realm-searchview#14]
Hey Torben.

Iam using your searchview ( compile 'com.github.thorbenprimke:realm-searchview:0.9.4' ) in my app project, while also using the Realm plugin. 
Iam using the Realm plugin 1.1.0 like the version in searchview?.  

When building the apk iam getting the DublicateFileExpetion due to multible .so files.
If i use 
packagingOptions {
     pickFirst("lib/armeabi/librealm-jni.so")
      ...
}
I can build the apk, but during runtime i get a java.lang.AbstractMethodError: abstract method "io.realm.RealmObject io.realm.internal.RealmProxyMediator.copyOrUpdate(io.realm.Realm, io.realm.RealmObject, boolean, java.util.Map)".

Have any clues to why this happens?  Iam assuming that i should still use the plugin while importing searchview?

**Comment by cgillions** [comment]
I faced a similar issue. Go to both the Realm github and the SearchView github and make sure both versions are up to date.
