### ISSUE TITLE
Support for of Model subset

### ISSUE THREAD

**Issue by cwalmsley** [thorbenprimke/realm-searchview#16]
Thanks for this great library.

It would be great if you could consider the following use case for inclusion in an upcoming release.

For example: take a Realm model Vehicles, with an Attribute Type which says if the object is a Car, Motorcycle, Truck.

We would like to display an activity containing a RealmSearchView to allow searching only the Cars from this model. To do this there would need to be a way of adding another condition to the RealmQuery for the required attribute.

I have created a fork with the changes that I have made for my own project to satisfy this use case.
https://github.com/HarvestYield/realm-searchview/commit/3ccd3eeb226be4405a8d34409232e5a40861acdf
(please ignore the deletion of RealmSearchView.java in that commit)

**Comment by reline** [comment]
@cwalmsley I took a different approach to solving this issue by passing in a RealmResults which was queried properly beforehand instead of a Realm instance. My fork is here [`GPSInsight@d1c9181`](https://github.com/GPSInsight/realm-searchview/commit/d1c91817880defbe487cb32300e286cabd3e28a7)

**Comment by cwalmsley** [comment]
Hi @Reline - that looks like a better approach. Thanks!

**Comment by reline** [comment]
@cwalmsley Just found a bug with my method. Each time the RealmResults is filtered, the results are narrowed down. This means searching "foo", then clearing your search and searching for "bar" will only return results that contain both "foo" and "bar". I'm working on a fix for it.

**Update**
So I'm now extending Realm's `RealmRecyclerViewAdapter` which you can find [here](https://github.com/realm/realm-android-adapters) but the concept should fundamentally be the same when extending thorbenprimke's. https://github.com/GPSInsight/realm-searchview/commit/1f4c41cd1309d1ba4214996a17c221fcf049aadd
