### ISSUE TITLE
Allow automatic updates from Realm

### ISSUE THREAD

**Issue by reline** [thorbenprimke/realm-searchview#17]
Currently, the `RealmSearchAdapter` overrides `RealmBasedRecyclerViewAdapter` and always passes `false` to autoUpdate (third parameter).

``` java
public RealmSearchAdapter(@NonNull Context context, @NonNull Realm realm, @NonNull String filterKey, boolean useContains, Case casing, Sort sortOrder, String sortKey, String basePredicate) {
        super(context, (RealmResults)null, false, false);
        ...
    }
```

It would be nice to add this as another customizable feature.

**Comment by scimetfoo** [comment]
Has any progress been made on this? You'd also have to pass the data, I believe.

**Comment by reline** [comment]
@Murtaza0xFF I've actually created my own version which takes an `OrderedRealmCollection` and provides this option :) https://github.com/Reline/realm-searchadapter

**Comment by scimetfoo** [comment]
Awesome! I'll be using the bits you updated by overriding those methods. 

Thank you!
