### ISSUE TITLE
Filter data by property

### ISSUE THREAD

**Issue by tomqz** [thorbenprimke/realm-searchview#19]
Hi, I have a question. When I'm populating my data with my Contact model, my filter key is "name". But I want to search only by property isFavorite == true - not all contacts. How can i achieve that with the RealmSearchAdapter?

And how does the basePredicate property works?

Thanks! :)

**Comment by johanfuen9** [comment]
Hi.

This work for me:

Add this method to RealmSearchAdapter class
        

> @Override
>         public void filter(String input) {
>             RealmQuery where = this.realm.where(Cliente.class).equalTo("estado","A");
>             if(!input.isEmpty()) {
>                where = where.contains(this.filterKey, input, Case.INSENSITIVE);
>             }
>             RealmResults businesses;
>             businesses = where.findAllSorted("nom", Sort.ASCENDING);
>             this.updateRealmResults(businesses);
>         }

and update `super.realmResults = clientes` on constructor;

Sorry for my english.
