### ISSUE TITLE
Error:Plugin with id 'com.zeroturnaround.jrebel.android' not found.

### ISSUE THREAD

**Issue by Freshman111** [thorbenprimke/realm-searchview#2]
I found this error

**Comment by Freshman111** [comment]
//apply plugin: 'com.zeroturnaround.jrebel.android'  
I closed this line and it work

**Comment by thorbenprimke** [comment]
Hmm. That line should be ignored if you don't have jRebel installed. I'll remove it though.

**Comment by thorbenprimke** [comment]
Closing as it shouldn't cause a problem.
