### ISSUE TITLE
Customisability

### ISSUE THREAD

**Issue by cgillions** [thorbenprimke/realm-searchview#20]
I would like my search input to be a separate element to the results element.

I need input to come from a text view at the top of my fragment, and the results to be displayed underneath a header in a different part of the view.

From what I can tell the input / results elements are tightly joined, I have been unable to customise them so far.

**Comment by gugakatsi** [comment]
+great idea

**Comment by matthewkrueger** [comment]
+1 here. @thorbenprimke is there any option to customize the look of the search box?  I love your library and how simple it is to use, but the search bar's look doesn't fit in well with my app's design.  Any ideas?

**Comment by 4goodapp** [comment]
@matthewkrueger I had the same issue about the app's design, you can find the realm_search_view.xml file ilocated in the libraries section > realm-searchview > res > layout.
