### ISSUE TITLE
Unable to access internal EditText

### ISSUE THREAD

**Issue by SandNerd** [thorbenprimke/realm-searchview#3]
I'm unable as of now to access and change the behavior of the internal `EditText`. Examples of What usual customizations:
`setOnEditorActionListener`
`addTextChangedListener`

Btw, thank you so much for the library. I'm using it as a replacement for `AutoCompleteTextView` which is broken on realm.

**Comment by thorbenprimke** [comment]
hey @sahal2080 - Good feedback and thanks for opening the issue. It's nice to see people use the library.

Totally makes sense why you would want to further customize it and thus those / other methods need to be exposed. I'll see about getting around to adding this over the weekend.
