### ISSUE TITLE
Failed to resolve: com.github.thorbenprimke:realm-searchview:0.9.6

### ISSUE THREAD

**Issue by dainq57** [thorbenprimke/realm-searchview#32]
I got this issue when I try complie. Plz help me~

**Comment by alexandresnunes** [comment]
I had the same problem!
Have someone solved this issue?

**Comment by RossCradock** [comment]
I had the same issue as this when I updated the SDK and had to add "maven.google.com" to the project gradle file instead of "jitpack.io". But you can add 2 maven links like this in the project gradle file:
```
allprojects {
    repositories {
        jcenter()
        maven { url "https://maven.google.com" }
        maven { url "https://jitpack.io" }
    }
}
```
