### ISSUE TITLE
Filter follow many columns

### ISSUE THREAD

**Issue by khangpv202** [thorbenprimke/realm-searchview#5]
i saw it very useful lib but how about filter many columns and sort it by some conditions such as firstColumn is "DESC" and secondColumn is "ASC".

**Comment by thorbenprimke** [comment]
Good point, @khangpv202. I'll see about adding support for more filtering.

I actually myself thought about adding support for supplying a separate query/filters for the empty state to for example recently selected items as long as nothing has been typed into the search bar.

**Comment by khangpv202** [comment]
@thorbenprimke,I think that in almost cases, they have a small set of data to view and with nothing has been typed, u shouldn't  select items. if u can allow user to set limited number of items and it will be load more at the end of listview and just sort in new loaded items. "supplying a separate query/filters", what does it mean? don't u migrate many conditions?

**Comment by koz01** [comment]
how to get row item id when click on item..plzzz help me

**Comment by thiagotn** [comment]
@koz01 Did you found a answer for your question? I have the same question.

**Comment by thiagotn** [comment]
@koz01 I found the solution for it. In your Class *RecyclerViewAdapter, just set and implement the OnClickListener. Something like this:

`@Override
    public void onBindRealmViewHolder(ViewHolder viewHolder, final int position) {
        final Restaurant restaurant = realmResults.get(position);
        viewHolder.restaurantItemView.bind(restaurant);
        viewHolder.itemView.setOnClickListener(
                new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        Log.i("INFO", "Item clicked: " + position);
                    }
                }
        );
    }`

**Comment by imidhuntv** [comment]
Can I filter through many columns now? Currently I see filter through only one column.

**Comment by khangpv202** [comment]
@imidhuntv  i'm usually check changed things but until now, it isn't support for filter many fields now. :(
@koz01 where do u want to  get row item id, i mean in adapter or in database of current clicked item
