### ISSUE TITLE
How to setOnItemClickListener to this layout

### ISSUE THREAD

**Issue by antoniomerlin** [thorbenprimke/realm-searchview#8]
How can we implement onItemClickListener to this realmRecyclerView

**Comment by JamesMcIntosh** [comment]
Looking at the RealmSearchView the RealmRecyclerView view is not exposed.

What you can do is add a click listener to each item and either implement your logic in the onClick or pass out your item to another listener.

```
    @Override
    public void onBindRealmViewHolder(ViewHolder viewHolder, int position) {
        final Blog blog = realmResults.get(position);
        viewHolder.blogItemView.bind(blog);
        viewHolder.blogItemView.setOnClickListener(
                new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                      // implement me - e.g. blogItemClickListener.onClick(blog);
                    }
                }
        );
    }
```

Have a look at the this example as it has a listener added to the footer view
https://github.com/thorbenprimke/realm-searchview/blob/bbc4c1cddc2ae04e514cda47e697ee09456baed2/example/app/src/main/java/co/moonmonkeylabs/realmsearchview/example/MainActivity.java

**Comment by antoniomerlin** [comment]
thanks.
